INSERT INTO consola (id, nombre, modelo, description, fabricante, precio, cantidad, ventas,fecha_lanzamiento, llegada_al_mercado, imagen) VALUES (1, 'Wii','RVL-001', 'Nintendo', 'Nintendo', 99.99,3, 2, '2006-11-12', '2021-12-08', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Wii_console.png/250px-Wii_console.png');
INSERT INTO consola (id, nombre, modelo, description, fabricante, precio, cantidad, ventas,fecha_lanzamiento, llegada_al_mercado, imagen) VALUES (2, 'Nintendo DS', 'FAT', 'Nintendo', 'Nintendo', 99.99,3, 2, '2004-11-05', '2021-12-08','https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Nintendo-DS-Lite-Black-Open.png/250px-Nintendo-DS-Lite-Black-Open.png');
INSERT INTO consola (id, nombre, modelo, description, fabricante, precio, cantidad, ventas,fecha_lanzamiento, llegada_al_mercado, imagen) VALUES (3, 'Play Station 3', 'FAT','Nintendo', 'Sony', 99.99,3, 2, '2006-11-12', '2021-12-08', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Sony-PlayStation-3-CECHA01-wController-L.jpg/960px-Sony-PlayStation-3-CECHA01-wController-L.jpg?20170727225248');
INSERT INTO consola (id, nombre, modelo, description, fabricante, precio, cantidad, ventas,fecha_lanzamiento, llegada_al_mercado, imagen) VALUES (4, 'XBOX 360', 'FAT','Nintendo', 'Microsoft', 99.99,3, 2, '2006-11-12', '2021-12-08', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Xbox-360-Pro-wController.jpg/250px-Xbox-360-Pro-wController.jpg');
INSERT INTO consola (id, nombre, modelo, description, fabricante, precio, cantidad, ventas,fecha_lanzamiento, llegada_al_mercado, imagen) VALUES (5, 'PSP', 'PSP-1000','Nintendo', 'Sony', 99.99,3, 2, '2006-11-12', '2021-12-08', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Sony-PSP-1000-Body.png/250px-Sony-PSP-1000-Body.png');

ALTER SEQUENCE consola_seq RESTART WITH 1000;

INSERT INTO juego (id, nombre, description, precio, cantidad, ventas, genero, num_jugadores, console_id, fecha_lanzamiento, llegada_al_mercado, ruta_imagen) VALUES (1, 'New Super Mario Bros Wii', 'Toma a una princesa secuestrada, un tirano en forma de reptil y un fontanero sin igual, aderézalo con mundos llenos de aventuras y mézclalo todo para crear un nuevo juego de Mario con un sabor familiar. Invita hasta tres amigos más y emprende esta nueva aventura ¡como nunca antes la habías jugado!', 29.99, 1, 0, 'Plataforma', 4, 1, '2009-11-12', '2021-12-08','https://art.gametdb.com/wii/cover3D/ES/SMNP01.png?1317736131');
INSERT INTO juego (id, nombre, description, precio, cantidad, ventas, genero, num_jugadores, console_id, fecha_lanzamiento, llegada_al_mercado, ruta_imagen) VALUES (2, 'Inazuma Eleven 2 Tormenta de Fuego', 'Quizás hayan ganado el Torneo Fútbol Frontrier, pero Mark y sus amigos van a necesitas habilidades de otro mundo para poder batirse en igualdad de condiciones en Inazuma Eleven 2. El popular juego de rol de fútbol vuelve con una nueva aventura en dos versiones: Inazuma Eleven 2: Tormenta de Fuego e Inazuma Eleven 2: Ventisca Eterna.', 29.99, 2, 1, 'J-RPG', 4, 2, '2012-03-12', '2021-12-08','https://art.gametdb.com/ds/box/EN/BEES.png?1502910585');
INSERT INTO juego (id, nombre, description, precio, cantidad, ventas, genero, num_jugadores, console_id, fecha_lanzamiento, llegada_al_mercado, ruta_imagen) VALUES (3, 'Cars Race-O-Rama', 'Únete a Rayo McQueen y corre contra nuevos personajes para hacerte con el trofeo de Race-O-Rama. Conduce y personaliza a Rayo McQueen, estrella de la película animada Cars. Enfréntate a nuevos personajes en una serie de pistas emocionantes. Corre contra un amigo en el vertiginoso modo multijugador.', 39.99, 2, 0, 'Carreras', 2, 3, '2009-11-30', '2021-12-08','https://art.gametdb.com/ps3/cover/ES/BLES00620.jpg?1404248226');
INSERT INTO juego (id, nombre, description, precio, cantidad, ventas, genero, num_jugadores, console_id, fecha_lanzamiento, llegada_al_mercado, ruta_imagen) VALUES (4, 'Cars', 'Únete a Rayo McQueen y corre contra nuevos personajes para hacerte con el trofeo de Race-O-Rama. Conduce y personaliza a Rayo McQueen, estrella de la película animada Cars. Enfréntate a nuevos personajes en una serie de pistas emocionantes. Corre contra un amigo en el vertiginoso modo multijugador.', 39.99, 2, 0, 'Carreras', 2, 4, '2009-11-30', '2021-12-08','https://cdn-products.eneba.com/resized-products/QSJevhfSKVAalNRa477NStt6-iGLy0EjPD_4JU5khec_350x200_1x-0.png');
INSERT INTO juego (id, nombre, description, precio, cantidad, ventas, genero, num_jugadores, console_id, fecha_lanzamiento, llegada_al_mercado, ruta_imagen) VALUES ( 'https://art.gametdb.com/wii/cover3D/ES/RMCP01.png?1528143761' );

ALTER SEQUENCE juego_seq RESTART WITH 1000;

INSERT INTO consola_juegos (consola_id, juegos_id) VALUES ( 1, 1 );
INSERT INTO consola_juegos (consola_id, juegos_id) VALUES ( 2, 2 );
INSERT INTO consola_juegos (consola_id, juegos_id) VALUES ( 3, 3 );
INSERT INTO consola_juegos (consola_id, juegos_id) VALUES ( 4, 4 );